project:
  type: book

book:
  title: "EI1039 - 2026/2027"
  author: "Carlos Granell"
  description: "Diseño de Software"
  date: today
  repo-url: https://github.com/cgranell/ei2639
  repo-branch: main
  repo-actions: [source, edit, issue]
  reader-mode: true
  chapters:
    - index.qmd
    - materials/01_architecture.qmd
    - materials/design_patterns.qmd
    - references.qmd
  
format:
  html:
    theme: [default, styles/edav3.scss]
    highlight-style: styles/joyce.theme
    callout-icon: false
    code-tools: false
    
bibliography: references.bib
citations-hover: true
citation-location: document
    
knitr:
  opts_chunk: 
    fig.align: center
    out.width: 70%
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: true

editor: source




