# Fundamentos de arquitectura

## ¿Qué es una arquitectura de software?


El término **arquitectura** tiene multiples significados según el contexto. En ingeniería de software/sistemas, ¿de qué hablamos cuando decimos **arquitectura software**? 

- ¿Nos referimos a una aplicación móvil?
- ¿A una librería software?
- ¿O una aplicación empresarial?
- ¿Tal vez una red de sensores desplegados en la ciudad junto a un centro (hub) de datos?
- ¿O simplemente el conjunto de diagramas de clases u casos de usos asociados?
- ¿Una red de *data centers* como los que posee Meta, Google, etc.?

Es importante definir, o al menos caracterizar, el concepto de arquitectura de software así como las implicaciones en el diseño y desarrollo de una arquitectura de software. A parte de programador o analista, podrías dedicarte al desarrollo de arquitecturas de software en el futuro. ¿Lo has pensado como profesión?

::: {.callout-tip}
## **Slide Deck** 

::: slides
[Conceptos, roles y compromisos](https://cgranell.github.io/ei1039-uji/materials/01-arquitectura-conceptos.html)
:::

:::


## Dimensiones de un arquitectura software

Según [@richards2020], no es fácil definir el concepto de arquitectura software. Una forma altrenativa ed hacerlo caracterizar el concepto a través de sus aspectos más destacables. Los autores utilizan el término *dimensión* para agrupar estos aspectos clave de la siguiente forma:

- Estructura o estilo

- Características de la arquitectura

- Decisiones o reglas

- Principios de diseño


### Características de la arquitectura de software


Ahora nos centramos en la dimensión de **características de la arquitectura**, que engloba todos aquellos aspectos, criterios y requisitos no funcionales (términos terminados generalmente en *-idad*, como seguridad, fiabilidad, escalabildiad, etc.) que una determinada arquitectura debe cumplir (o al menos tener en cuenta) para garantizar un funcionamiento correcto y deseable.

::: {.callout-tip icon=false}
## **Slide Deck** 

::: slides
[Características de una arquitectura](https://cgranell.github.io/ei1039-uji/materials/01-arquitectura-caracteristicas.html)
:::

:::

### Estructura de la arquitectura de software

La estructura o el estilo es otra dimensión de la arquitectura de software [@richards2020]. Quizás mucho más conocida y popular, y precisamente por eso, existe la errónea tendencia a reducir cualquier arquitectura de software únicamente a la dimensión de estructura o estilo. Hablamos de arquitectura **en capas** o basada en **microservicios**, como si la dimensión de la estructura abarcara en sí misma toda la complejidad de una arquitectura de software.

::: {.callout-tip icon=false}
## **Slide Deck** 

::: slides
[Estilos de una arquitectura](https://cgranell.github.io/ei1039-uji/materials/01-arquitectura-estilos.html)
:::

:::