# Principios de diseño de software


## Principios de la programación orientada a objetos (POO)


<!-- TODO: Narrativa de los Principios básicos de diseño de software (presentes en casi todos los patrones de diseño) aqui a partir de la presentación https://cgranell.github.io/ei2639-slides/materials/01-course-content/ -->

Principios básicos de diseño de software (presentes en casi todos los patrones de diseño)

### Encapsula lo que varía y sepáralo de lo que no cambia 



### Programa a una interfaz, no a una implementación



### Favorece la composición sobre la herencia


## Principios SOLID

Varios autores ([Michael Feathers](https://michaelfeathers.silvrback.com/), [Robert C. Martin](https://blog.cleancoder.com/), etc. ) han contribuido a definir una serie de principios (recomendaciones, etc.) para que desarrolladores/programadores generen software de *calidad*. ¿Y qué entendemos por software de calidad? Software que sea:

- robusto y estable, 
- reutilizable y mantenible, 
- escalable, es decir, que se pueda modificar/extender fácilmente.


Sin embargo, que el código resultante sea robusto y estable por un lado, pero que también sea fácilmente extendible y reutilizable por otro, parece que sean objetivos contradictorios. En ingeniería y desarrollo de software, tenemos dos conceptos que tenemos que balancear adecuadamente al mismo tiempo para producir software de calidad.


::: {.callout-note title="Definición" icon=true}

**Acoplamiento** indica el grado de *interdependencia* entre entidades/componentes de software (ya sean clases, métodos, módulos, funciones, etc. ). Si dos componentes son completamente independientes entre sí, entonces están *desacoplados*.

:::

Como ingenieros/as de software, queremos que el software generado tenga **un bajo acomplamiento**.



::: {.callout-note title="Definición" icon=true}

**Cohesión** indica el grado en que entidades/componentes de software independientes se combinan para alcanzar un resultado (comporatemeionte, etc) mejor que si trabajaran por separado. Se refiere a la forma en que podemos agrupar componentes de software.


:::

Como ingenieros/as de software, queremos que el software generado tenga **una alta cohesión**.



Los principios SOLID están estrechamente relacionados con el uso de patrones de diseño, ya que las solucciones conceptuales de muchos patrones apuntan directamente a uno o varios de los principios SOLID. Luego, cuando utilizas patrones de diseño de forma eficaz, estarás poniendo en práctica alguno de los principios SOLID para que el código resultante sea de la mejor calidad posible. 

Los 5 principios SOLID de diseño de aplicaciones de software son:

- **S** – Single Responsibility Principle (SRP), *principio de responsabilidad única*
- **O** – Open/Closed Principle (OCP), *principio de abierto/cerrado*
- **L** – Liskov Substitution Principle (LSP), *principio de sustitución de Liskov*
- **I** – Interface Segregation Principle (ISP), *principio de segregación de la interfaz*
- **D** – Dependency Inversion Principle (DIP), *principio de inversión de dependencia*


<!-- TODO: Transformar slides SOLID en texto y eliminar slides -->

::: {.callout-tip title="Slide Deck"}

[Principios SOLID](https://cgranell.github.io/ei2639-slides/materials/05-solid-principle/)

:::
